//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicomotorStageControl_v2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IndicatorCOMPort {
            get {
                return ((string)(this["IndicatorCOMPort"]));
            }
            set {
                this["IndicatorCOMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.002")]
        public decimal AvgNegativeStepSize_um {
            get {
                return ((decimal)(this["AvgNegativeStepSize_um"]));
            }
            set {
                this["AvgNegativeStepSize_um"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.002")]
        public decimal AvgPositiveStepSize_um {
            get {
                return ((decimal)(this["AvgPositiveStepSize_um"]));
            }
            set {
                this["AvgPositiveStepSize_um"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StageMovementCreepUp {
            get {
                return ((bool)(this["StageMovementCreepUp"]));
            }
            set {
                this["StageMovementCreepUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StageMovementSlowDownVelocity {
            get {
                return ((int)(this["StageMovementSlowDownVelocity"]));
            }
            set {
                this["StageMovementSlowDownVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int StageMovementSlowDownDistance {
            get {
                return ((int)(this["StageMovementSlowDownDistance"]));
            }
            set {
                this["StageMovementSlowDownDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MicroscopeStageCOMPort {
            get {
                return ((string)(this["MicroscopeStageCOMPort"]));
            }
            set {
                this["MicroscopeStageCOMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IndenterCOMPort {
            get {
                return ((string)(this["IndenterCOMPort"]));
            }
            set {
                this["IndenterCOMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal IndenterCalibration_RawNoProbe {
            get {
                return ((decimal)(this["IndenterCalibration_RawNoProbe"]));
            }
            set {
                this["IndenterCalibration_RawNoProbe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal IndenterCalibration_RawWithProbe {
            get {
                return ((decimal)(this["IndenterCalibration_RawWithProbe"]));
            }
            set {
                this["IndenterCalibration_RawWithProbe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal IndenterCalibration_ProbeWeight_mg {
            get {
                return ((decimal)(this["IndenterCalibration_ProbeWeight_mg"]));
            }
            set {
                this["IndenterCalibration_ProbeWeight_mg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal IndenterCalibration_Diameter_um {
            get {
                return ((decimal)(this["IndenterCalibration_Diameter_um"]));
            }
            set {
                this["IndenterCalibration_Diameter_um"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal IndenterCalibration_SpringConst_N_m {
            get {
                return ((decimal)(this["IndenterCalibration_SpringConst_N_m"]));
            }
            set {
                this["IndenterCalibration_SpringConst_N_m"] = value;
            }
        }
    }
}
